### ISSUE TITLE
Postgres and migration script not able to run in windows 10

### ISSUE THREAD

**Issue by nileshkant** [mkosir/express-typescript-typeorm-boilerplate#73]
I have tried to run `npm run docker:dev` and the following error promted using powershell on Windows 10 HOME.

- Postgress  `database system was interrupted;`
   although its inturupted its showing running in docker
```
   database system is ready to accept connections
  be_boilerplate         | Server running on port 4000
  be_boilerplate         | Database connection success. Connection name: 'default' Database: 'boilerplate'
```
Here is docker log

![image](https://user-images.githubusercontent.com/30167802/122019401-5ad24f00-cde1-11eb-8702-011af1733228.png)

- migrate script is not working `missing script: migration:generate`
- seed script is not working `missing script: seed:run`

![image](https://user-images.githubusercontent.com/30167802/122018306-5bb6b100-cde0-11eb-9a18-900d63c7bed2.png)

Please give any solution for this.
Thanks

**Comment by mkosir** [comment]
Hi @nileshkant currently I'm running it only on Linux and macOS, but haven't tested on windows. It would be great if you can take a stab at this and make it work also on Windows 🚀

**Comment by nileshkant** [comment]
Any possible way that you can write scripts for Powershell. Because Windows can't able to execute the bash file.

**Comment by mkosir** [comment]
Not so familiar with Windows operating system, but I thought its possible to use Windows Subsystem for Linux (WSL).   Nevertheless scripts that are failing should work independent of the underlying system, since they are all executed inside docker container, so not sure really what is causing the issue on Windows.

**Comment by Jonty16117** [comment]
Actually I think the problem is that the environment variables are not loaded in the windows, using cross-env solves the problem for all the platforms once and for all 👍✌️

**Comment by mkosir** [comment]
@nileshkant maybe you can try with (Windows) [proposed solution](https://github.com/mkosir/express-typescript-typeorm-boilerplate/discussions/182) as @Jonty16117 mentioned.
